# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = ""
  weight = 10

[[main]]
  name = "Posts"
  url = "post/"
  weight = 20

[[main]]
  name = "Publications"
  url = "publication/"
  weight = 30

##[[main]]
##  name = "Projects"
##  url = "project/"
##  weight = 40

[[main]]
  name = "About me"
  url = "about/"
  weight = 50

[[main]]
  name = "Talks"
  url = "Talks/"
  weight = 60

##[[main]]
##  name = "Agenda"
##  url = "agenda/"
##  weight = 60
  
[[main]]
  name = "Teaching"
  url = "teaching/"
  weight = 70
  
[[main]]
  name = "Shiny-GPS"
  url = "shinygps/"
  weight = 90  
  
[[main]]
  name = "Contact"
  url = "#contact/"
  weight = 90
  

 [[main]]
    name = "CV"
    url = "files/cv.pdf"
    weight = 70
