---
title: "MICE exercises"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
---

# Intro {.sidebar}

This dashboard covers the practical exercise materials for the [***Missing Data module in Survey Data Analysis***](https://osiris.uu.nl/osiris_student_uuprd/OnderwijsCatalogusSelect.do?selectie=cursus&cursus=201300001&collegejaar=2020&taal=en)

---

Module instructors: <br>
[Stef van Buuren](https://www.stefvanbuuren.name) and [Gerko Vink](https://www.gerkovink.com) <br>

---

| When? | What?        | Where? |
|-------|--------------|--------|
| Wk 45 | Exercise 1-3 | online |
| Wk 46 | Exercise 4-6 | online |

---

# Week 45: 8-12 Nov

## Column 1

### Exercises for this week

The following exercises are walkthroughs that take you through the process of drawing valid inferences from incomplete data sets with `mice` in `R`. 

- [Exercise 1](Exercises/Exercise 1/1.-Ad_hoc_methods.html)
- [Exercise 2](Exercises/Exercise 2/2.-Convergence_and_pooling.html)
- [Exercise 3](Exercises/Exercise 3/3.-Missingness_inspection.html)

### Discussion of Exercises

Video walkthroughs for this week's exercises:

- [Exercise 1 walkthrough](https://www.dropbox.com/s/cb2yptcr6dfv0u8/Exercise%201.mp4?dl=0)
- [Exercise 2 walkthrough](https://www.dropbox.com/s/2118fbiirf91mq0/Exercise%202.mp4?dl=0)
- [Exercise 3 walkthrough](https://www.dropbox.com/s/77ckcmwjy82wl9w/Exercise%203.mp4?dl=0)

# Week 46: 15-19 Nov

## Column 1

### Exercises for this week

The following exercises are walkthroughs that take you through the process of drawing valid inferences from incomplete data sets with `mice` in `R`. 

- [Exercise 4](Exercises/Exercise 4/4.-Passive-imputation_post_processing.html)
- [Exercise 5](Exercises/Exercise 5/5.-Combining_inferences.html)
- [Exercise 6](Exercises/Exercise 6/Multi_level_data.html)

### Discussion of Exercises

Video walkthroughs for this week's exercises is available from Thursday 19 November.

- [Exercise 4 walkthrough](https://www.dropbox.com/s/9u9ncf1qgxj3g9u/Exercise%204.mp4?dl=0)
- [Exercise 5 walkthrough](https://www.dropbox.com/s/9ykzcci5kf5lguw/Exercise%205.mp4?dl=0)
- [Exercise 6 walkthrough]()
